swagger: "2.0"
info: {}
paths: {}
definitions:
  float:
    title: float
    type: object
  models.ZDTCustomer.Customer:
    title: Customer
    type: object
  models.ZDTProduct.ProductList:
    title: ProductList
    type: object
